src/components/sectionAdmin/products/AllProducts.jsx, src/pages/ProductAll.jsx, src/pages/ProductCat.jsx, src/pages/ProductDog.jsx
=> Feature ProdutAll

src/components/common/ChatRobot.jsx, src/components/common/Layout.jsx, src/pages/Blogs.jsx, src/pages/ProductCat.jsx, src/pages/ProductPage.jsx
新增 Blog 頁面：新增 文章列、搜尋文章欄、最新文章欄、文章分類欄
修正 ProductPage 細節：max-width、GoToHome鍵調整
=> 新增 Feature/blog

src/api/blogs.js
=> Blog 更新baseUrl

src/api/blogs.js, src/pages/Blogs.jsx
=> Blog 置頂功能問題解決、文章分類問題解決

src/api/blogs.js, src/components/common/GoTop.jsx, src/pages/Blogs.jsx
Blog：新增搜尋功能(未完成)
GoTop：修正waring 問題
=> Blog：新增搜尋功能(未完成)

src/pages/ProductAll.jsx, src/pages/ProductCat.jsx, src/pages/ProductDog.jsx, src/pages/ProductPopCart.jsx
Feature/product all：串接 Product API
=> Feature/product all：串接 Product API 

src/pages/ProductPopCart.jsx
=>  Feature/product all ：新增點擊彈跳加入購物車模組

src/pages/Blogs.jsx
Feature/blog: 置頂功能使用sort排序功能調整
=> Feature/blog: 置頂功能使用sort排序功能調整

src/components/common/HomeLinkWrapper.jsx, src/pages/Blogs.jsx, src/pages/ProductPage.jsx
新增Blog RWD樣式：
1. 992px 以下 新增 select 分類選項
2. 上方新增搜尋列表
調整 HomeLinkWrapper：
992px 以下靠左
=> Feature/blog：新增Blog RWD樣式、調整 HomeLinkWrapper

src/assets/icons/index.js, src/pages/ProductAll.jsx, src/pages/ProductCat.jsx, src/pages/ProductDog.jsx
Feature/ProductAll：新增Product 價格升降排序
寫到邏輯混亂
=> Feature/ProductAll：新增Product 價格升降排序

src/pages/Home.jsx, src/pages/ProductItem.jsx, src/pages/SingleProduct.jsx
SingleProduct 細節修正：加購選項、商品詳情圖片渲染、商品圖片點擊後預覽切換
=> Feature/ProductAll：SingleProduct 細節修正、調整ProductItem css樣式

src/App.js, src/api/userAuth.js, src/components/common/SidebarModal.jsx, src/pages/Blogs.jsx, src/pages/Order.jsx, src/pages/SingleOrder.jsx
新增查詢訂單API：修正 userAuth 抓 localStorage usertoken
修改Blog：新增 blogFilter 條件、新增 useContext，點擊 SidebarModal 上的 Blog 可以到貓貓狗狗分類文章
=> Feature/product all：新增查詢訂單API、修改Blog

src/components/common/CartModal.jsx, src/pages/Cart.jsx, src/pages/ProductPopCart.jsx, src/pages/SingleProduct.jsx, src/store/productSlice.js
SingleProduct 引用購物車 Redux。
調整購物車邏輯，當加入購物車時，依照當前 count 數量修正購物車數量。
=> Feature/ProductAll：SingleProduct 引用購物車 Redux

src/pages/ProductPopCart.jsx, src/pages/SingleOrder.jsx
Feature/product all：SingleOrder 新增查無訂單錯誤處理
=> Feature/product all：新增查無訂單錯誤處理

README.md
=> 修改 README 圖檔

src/components/common/ChatRobot.jsx, src/components/common/GoTop.jsx
=> GoTop、ChatRobot 細節調整

src/pages/Cart.jsx
Cart useEffect window.scrollTo 調整
=> Cart useEffect window.scrollTo 調整

src/pages/Cart.jsx
1. 購物車新增點擊品名引導至商品頁
2. 收件人同購買人資料勾選時可複製使用
=> Cart 購物車細節調整

public/index.html, src/components/common/CartModal.jsx, src/pages/Cart.jsx
1. fb chatbot  測試
2. cart select default value修正
=> cart select default value修正

package-lock.json, package.json, public/index.html, src/components/common/CartModal.jsx, src/components/common/ChatRobot.jsx
=> fb chat test

public/index.html, src/components/common/ChatRobot.jsx
=> chatbot細節調整 index.html調整

public/index.html, src/components/common/ChatRobot.jsx
Feature/product all: 移除manifest.json
=> Feature/product all: 移除manifest.json

src/pages/Blogs.jsx, src/pages/ProductPopCart.jsx, src/pages/SingleProduct.jsx, src/store/productSlice.js
調整購物車加入規則，選擇數量後可累加
調整 Blog 搜尋，查詢成功或失敗後清除 value
=> Feature/product all：調整購物車加入規則、調整 Blog 搜尋

src/pages/ProductPopCart.jsx, src/pages/SingleProduct.jsx
=> 修改立即購買購物車邏輯

src/components/common/LoginModal.jsx, src/pages/ProductAll.jsx, src/pages/ProductItem.jsx
=> fb appID 修正

src/components/common/LoginModal.jsx
=> 修改 fb login

README.md, src/pages/SingleProduct.jsx
=> 更新Readme.md
